name: CI/CD Local Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check runner
        run: whoami && pwd

      - name: Update code
        run: git -C /home/gitrunner/DockerComposeBuild pull

      - name: Build images
        run: |
          cd /home/gitrunner/DockerComposeBuild
          docker compose build

      - name: Deploy (zero-downtime-ish)
        run: |
          cd /home/gitrunner/DockerComposeBuild
          docker compose up -d --build --remove-orphans
          docker compose up -d nginx

      - name: Wait for app
        run: |
          until curl -s http://localhost > /dev/null; do
            echo "Waiting..."
            sleep 20
          done

      - name: Health check
        run: curl --fail http://localhost
